'use client'

import { FileText } from 'lucide-react'

export default function EmployeeDocumentsPage() {
  return (
    <div className="space-y-6">
      <div className="rounded-xl border border-border bg-accent-light px-6 py-4 text-center">
        <h1 className="text-xl font-semibold text-text-primary">
          My <span className="text-accent">Documents</span>
        </h1>
      </div>

      <div className="flex flex-col items-center justify-center rounded-xl border border-border bg-background py-16">
        <FileText className="mb-4 h-12 w-12 text-text-muted" />
        <p className="text-sm text-text-muted">No documents available yet.</p>
        <p className="mt-1 text-xs text-text-muted">
          Your payslips and HR letters will appear here once generated by your admin.
        </p>
      </div>
    </div>
  )
}
